### ISSUE TITLE
grigio:babel is deprecated

### ISSUE THREAD

**Issue by jperl** [meteor-velocity/velocity-helpers#7]
It seems like it is no longer compatible with 1.2

![](https://camo.githubusercontent.com/1dccab0d1ddcf1cec4d9e14072b070940987c3af/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f3058324530783376326a3337314b3231316533372f53637265656e25323053686f74253230323031352d30392d32312532306174253230372e30312e3339253230504d2e706e67)

**Comment by samhatoum** [comment]
we should be able to replace this with the `ecmascript` packagei in the new [velocity release](https://github.com/meteor-velocity/velocity/blob/meteor-1.2/package.js#L27)

**Comment by Sanjo** [comment]
Will do it later today.
