### ISSUE TITLE
Template helpers with Template.instance()

### ISSUE THREAD

**Issue by ShockiTV** [meteor-velocity/velocity-helpers#8]
Hi,
is it possible to test any template helpers which use Template.instance() ?
It is always null for me and I cant think of a way how to scope it correctly.

**Comment by ghost** [comment]
Yes like this:

```
const view = Blaze.render(...);
const instance = view.templateInstance();
```

Check out the documentation:
- http://docs.meteor.com/#/full/blaze_renderwithdata
- http://docs.meteor.com/#/full/blaze_view
